### ISSUE TITLE
Calling functions with trait constraints doesn't seem to work correctly

### ISSUE THREAD

**Issue by jstasiak** [kitlang/kit#10]
- **Kit version:** 5c1e92607958
- **OS/Platform:** Mac

### **Describe the problem. What did you see? What did you expect to see?**

This code should (according to https://www.kitlang.org/examples.html#trait-constraints) write `"hello"` to `/tmp/greeting`:

```kit
import kit.sys.file;

function greet[W: Writer](w: W) {
    w.write("hello");
}

function main() {
    var f = File.write("/tmp/greeting");
    greet(f);
}
```

It produces a warning when building, but it builds successfully:

```
[2018-10-04 13:44:22.247710] ===> compiling main.greet
[2018-10-04 13:44:22.248143] /usr/bin/cc -Ibuild/include -c build/lib/main/kit_greet.c -o build/obj/main/kit_greet.o -D_GNU_SOURCE -D_BSD_SOURCE -D_DEFAULT_SOURCE '-std=c99' -pedantic -O3 -Os -U__BLOCKS__ -Wno-expansion-to-defined -Wno-gnu-zero-variadic-macro-arguments
build/lib/main/kit_greet.c:5:30: warning: incompatible pointer types passing 'FILE **' (aka 'struct __sFILE **') to parameter of type 'char *' [-Wincompatible-pointer-types]
    kit_sys_file_File__write(&w);
                             ^~
build/include/main.h:85:40: note: passing argument to parameter 'path' here
FILE * kit_sys_file_File__write(char * path);
                                       ^
1 warning generated.
```

After running it:

```
% ls -h /tmp/greeting
ls: /tmp/greeting: No such file or directory
% ./main 
% ls -lh /tmp/greeting
-rw-r--r--  1 kuba  wheel     0B Oct  4 13:57 /tmp/greeting
```

I had a look at the generated code, see below.

`lib/kit_main.c`:

```c
#include "main.h"

int main()
{
    {
        FILE * f = kit_sys_file_File__write((char *) "/tmp/greeting");
        main_greet__fac4fab0400c4242(f);
    }
    return 0;
}
```

`lib/main/kit_greet.c':

```c
#include "main.h"

void main_greet__fac4fab0400c4242(FILE * w)
{
    kit_sys_file_File__write(&w);
}
```

And `kit_sys_file_File__write` (in lib/kit/sys/file/kit_File.c) is the static function that opens the file in the first place - it's done again by `main_greet...` above.

`lib/kit/sys/file/kit_File.c':

```c
// ...
FILE * kit_sys_file_File__write(char * path)
{
    return fopen(path, (char *) "w");
}

//...
```

After some digging it seems that the presence of the static `write` function (the same name as the `write` function in the `Write` trait) in the `File` Abstract silences the issue, because if the names differ the code won't compile and we know right away something's fishy:

```kit
% cat ../kitbox/main.kit      
import kit.sys.file;

trait Blablaber[T] {
    public function blabla(value: T): Void;
}

implement Blablaber[CString] for File {
    public function blabla(value: CString) {
        fwrite(value, sizeof Char, strlen(value), this);
    }
}

function greet[B: Blablaber](b: B) {
    b.blabla("hello");
}

function main() {
    var f = File.write("/tmp/greeting");
    greet(f);
}

% kitc -s ./std -s ../kitbox main
[2018-10-04 14:05:24.635907] ===> parsing and building module graph
[2018-10-04 14:05:24.647979] ===> processing C includes
[2018-10-04 14:05:24.852206] ===> resolving module types
[2018-10-04 14:05:24.855792] ===> typing module content
----------------------------------------
Error: ../kitbox/main.kit:14: Field access is not allowed on FILE

  @../kitbox/main.kit:14:5-12
      14        b.blabla("hello");
                ^^^^^^^^

[2018-10-04 14:05:24.865898] ===> total time: 0.230116s
[2018-10-04 14:05:24.866340] ERR: compilation failed (1 errors)
```

I tried to narrow the issue down and got lost somewhere around following/unifying types so I decided to leave a report instead, hope it helps.

**Comment by bendmorris** [comment]
The File API has been reworked slightly. It seems to work now and there's a test case to verify. Examples still need to be updated.

**Comment by jstasiak** [comment]
Wasn't the file API ok though? (I hope this is not a stupid question) It seems to me that it's about trait constraints (both in case of generic functions and casting) not fully working.

I'd expect the following to work with all three code blocks uncommented:

```kit
import kit.sys.file;

function fun[W: Writer](w: W) {
    w.write("woot3");
}

function main() {
    var f = File.write("/tmp/greeting");

    // 1.
    //var writer: Writer = f;
    //f.write("woot1");

    // 2.
    //(f as Writer).write("woot2");

    // 3.
    //fun(f);
}
```

If I try to compile the code above with the latest compiler (828881970de4) I get:

```
# 1st block uncommented
[2018-10-10 16:50:16.545868] ===> parsing and building module graph
[2018-10-10 16:50:16.590312] ===> processing C includes
[2018-10-10 16:50:17.201545] ===> resolving module types
[2018-10-10 16:50:17.228674] ===> typing module content
[2018-10-10 16:50:17.244480] ===> generating intermediate representation
----------------------------------------
Error: ../kitbox/asd.kit:11: Couldn't find underlying type for trait kit.io.Writer

  @../kitbox/asd.kit:11:5-27
      11        var writer: Writer = f;
                ^^^^^^^^^^^^^^^^^^^^^^^


# 2nd block uncommented
[2018-10-10 16:50:48.129314] ===> parsing and building module graph
[2018-10-10 16:50:48.171263] ===> processing C includes
[2018-10-10 16:50:48.783611] ===> resolving module types
[2018-10-10 16:50:48.811907] ===> typing module content
----------------------------------------
Error: ../kitbox/asd.kit:15: Function expected 3 arguments:

  function (Int, Ptr[Void], Size) -> Int

Called with 1 argument, and 3 implicits:

  - implicit trait kit.io.Writer
  - implicit (unknown type #86)
  - implicit kit.common.Box[trait kit.mem.Allocator]

  @../kitbox/asd.kit:15:6-23
      15        (f as Writer).write("woot2");
                 ^^^^^^^^^^^^^^^^^^



# 3rd block uncommented
[2018-10-10 16:51:19.793170] ===> parsing and building module graph
[2018-10-10 16:51:19.838036] ===> processing C includes
[2018-10-10 16:51:20.439659] ===> resolving module types
[2018-10-10 16:51:20.465329] ===> typing module content
[2018-10-10 16:51:20.480806] ===> generating intermediate representation
----------------------------------------
Error: ../kitbox/asd.kit:3: Couldn't find underlying type for trait kit.io.Writer

  @../kitbox/asd.kit:3:14
       3    function fun[W: Writer](w: W) {
                         ^
```

I can see how those would cleanly translate to C but on the other hand I may be just looking for some behaviour that's actually not desired, I'm curious now.

**Comment by jstasiak** [comment]
PS. If it's actually something that should work I'd be happy to work on this, but I'd need some guidance.

**Comment by bendmorris** [comment]
The way generics are designed in Kit, adding trait constraints to type parameters will constrain what can be used there, but generics still employ duck typing, so anything that successfully compiles when we substitute in the underlying type is acceptable. It's kind of a mix of Rust generics and C++ templates.

https://github.com/kitlang/kit/pull/18 adds syntax for calling a specific trait implementation method, so this would become:

```kit
function greet[W: Writer](w: W) {
    w.Writer.write("hello");
}
```

`w.Writer` gives you the trait implementation of Writer for w, instead of looking for a method on `w` itself.

I'll leave this open as there's still some room for improvement (notably we're not doing anything with parameter constraints yet.)

**Comment by jstasiak** [comment]
That's really cool, thanks for the extra explanation as well.

**Comment by bendmorris** [comment]
>I'll leave this open as there's still some room for improvement

Actually I'll go ahead and close it. There's a Trello ticket open for the remaining work, and I'm trying to move away from leaving GitHub issues open as todo items.
