### ISSUE TITLE
What C game engines does Kit (plan to) target?

### ISSUE THREAD

**Issue by coltonhurst** [kitlang/kit#104]
Not a bug- just curious! As Kit compiles to C, what game engines will Kit (or does Kit) target?

Thanks for the hard work!

**Comment by bendmorris** [comment]
It should be pretty easy to use with most. I'm writing an engine on top of SDL right now, and another user is targeting Raylib.

If you run into an engine that doesn't integrate smoothly, bring it up on [Discord](https://discordapp.com/invite/3va8Us9) and I'll take a look!

**Comment by bendmorris** [comment]
And btw - Discord is a good place for questions like this!

**Comment by RUSshy** [comment]
engines are always opinionated, people are never satisfied, i think best for kit is to have 2d/3d lib like monogame for c# and libgdx for java

**Comment by RUSshy** [comment]
@bendmorris i recently discovered kit, and i seen you work on a 2d engine, is there plan for 3d support ? https://github.com/bendmorris/krit

**Comment by bendmorris** [comment]
No plans for 3d support on that engine.
