### ISSUE TITLE
Weird bahaviour in the playgound's printf

### ISSUE THREAD

**Issue by tuket** [kitlang/kit#147]
### **Describe the problem. What did you see? What did you expect to see?**

In the [playgound](https://www.kitlang.org/playground.html).

I change this line:
```
    printf("%s, %s!", greeting.firstWord, greeting.secondWord);
```

to:

```
    printf("%s, %s %s %s %s %s!", greeting.firstWord, greeting.secondWord);
```
And it prints:
```
Hello, world Hello world (null) (null)!
```
I would expect either (if it's supposed to cycle)
```
Hello, world Hello world Hello world!
```
Or this
```
Hello, world (null) (null) (null) (null)!
```

**Comment by codehz** [comment]
I think it should be an undefined behavior, and (if possible) generate a warning (like GCC do
or even generate a compile-time error to avoid undefined behavior.

**Comment by bendmorris** [comment]
It actually does generate a warning (thrown by the C compiler) but the playground doesn't surface warnings. Having more formatting specifiers than arguments results in undefined behavior.

**Comment by tuket** [comment]
Cool, we can close this then
