### ISSUE TITLE
Using `match` as an expression

### ISSUE THREAD

**Issue by tekknolagi** [kitlang/kit#3]
- **Kit version:** 0.1.0
- **OS/Platform:** Mac

### **Describe the problem. What did you see? What did you expect to see?**

The docs say that `match` can be used as an expression. I would like to return the result of a match from a function. I can't figure out how to do so. Returning the match doesn't work -- Kit doesn't like wrapping it in parentheses -- and just leaving the match as the body of the function also does not work.

### **If this is a code issue, provide a minimal code example:**

```kit
enum Exp {
    IntLit(value: Int);
}

function toString(e: Exp): CString {
    return (match e {
        IntLit(v) => "hello";
        default => "uh oh";
    });
}

// OR this

function toString(e: Exp): CString {
    match e {
        IntLit(v) =>= "hello";
        default => "uh oh";
    })
}
```

The top toString is a syntax error and the bottom toString generates a function that does not return any value in C:

```c
char * ast__toString(struct ast__Exp e)
{
    if (e.__dsc == ast_Exp__IntLit)
    {
        int v = e.__var.variant_IntLit.value;
        (char *) "hello";
    }
    else
    {
        (char *) "uh oh";
    }
}
```

Additionally, it doesn't appear as though this would work anyway -- do the string literals live long enough?

**Comment by bendmorris** [comment]
The docs are optimistic; this is planned but not currently implemented. I'll correct that.

You can usually get the same effect pretty easily:

```
function toString(e: Exp): CString {
    match e {
        IntLit(v) => return "hello";
        default => return "uh oh";
    };
}
```

**Comment by bendmorris** [comment]
>Additionally, it doesn't appear as though this would work anyway -- do the string literals live long enough?

This is fine; the lifetime of string literals is static. It would however be UB to try to modify it (and currently Kit won't complain about that - you'll probably end up with a bus error at runtime.)

**Comment by tekknolagi** [comment]
Thank you @bendmorris! And awesome job with Kit. Nice language.

**Comment by bendmorris** [comment]
Removed match expressions from the website for now.
