### ISSUE TITLE
Generating temporary variable not in order

### ISSUE THREAD

**Issue by ustance** [kitlang/kit#4]
- **Kit version:** 0.1.0
- **OS/Platform:** Linux x64

Kit is generating temporary variable for **Player** struct in the beginning of a function, but it is critical to do it in order.

### **Kit and generated C:**

![img](https://i.imgur.com/Ew954Rc.png)

**Comment by bendmorris** [comment]
I just pushed a commit that should fix this - would you mind confirming?

**Comment by ustance** [comment]
Yep, everything is working fine now ~
