### ISSUE TITLE
Kit is unable to find string.h on macOS High Sierra

### ISSUE THREAD

**Issue by spencerking** [kitlang/kit#5]
- **Kit version:** 0.1.0
- **OS/Platform:** macOS High Sierra

### **Describe the problem. What did you see? What did you expect to see?**

Kit is unable to find string.h. Kit expects it in /usr/include/string.h, but it's actually contained with Xcode.app. @bendmorris suggested running `echo | gcc -E -Wp,-v -` to find all of my include paths. It turns out string.h was located at `/Applications/Xcode-9_4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include`.

**Comment by kitplummer** [comment]
For some reason 'includes' are not installed by default (really lame).  Ran into this issue after upping to Mojave.

Fix is buried in this post:  https://forums.developer.apple.com/thread/104296

Basically, just need to download the package that includes all the includes.

**Comment by bendmorris** [comment]
Now that kitc itself uses `gcc -E -Wp,-v -`, and we provide a macOS package, this should no longer be an issue.
